# Конфиг для оверрайда дефолтных настроек. Положите его в рабочую директорию, уберите суфикс .example и раскомментируйте нужные строки

[trakt]

# Запускать только эти цели:
# selected_targets = ["box", "point", "lseg"]

# Настройки afl
[fuzz_afl]
watch_dog = { limits = { last_path = "1h" } }
